# path to input directory with .bam files
input_dir: input

# path to output directory
output_dir: output

# path to reference genome
reference_genome: reference_genome/GRCh37-lite.fa

# cell identifiers to include in the analysis
sample_ids:
- SA928-A90553C-R44-C19
- SA928-A90553C-R45-C51
- SA928-A90553C-R64-C54
- SA928-A90553C-R67-C09
